name: Geo-Tracker CI Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código fuente
        uses: actions/checkout@v4

      - name: Configurar Node.js (v18)
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Instalar dependencias del Backend
        run: npm ci

      - name: Generar cliente de Prisma
        run: npx prisma generate

      - name: Ejecutar pruebas unitarias (Jest)
        run: npm run test

  test-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend # Ajusta la ruta de tu proyecto React si aplica

    steps:
      - name: Descargar código fuente
        uses: actions/checkout@v4

      - name: Configurar Node.js (v18)
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Instalar dependencias del Frontend
        run: npm ci

      - name: Compilar Frontend (Build Check)
        run: npm run build